### ISSUE TITLE
Mapjes voor verschillende onderdelen van het project

### ISSUE THREAD

**Issue by Tamrell** [slanghout/Heuristieken#1]
Hey Familie van de Kerkhof,
ik zie dat jullie nu alles in de head directory hebben staan, kijk nog even naar de voorbeeldgit van maarten: https://github.com/Maarten-vd-Sande/voorbeeldRepo
probeer ook mapjes te maken voor de code en de data (anders wordt het omschrijven van de code naar een nieuwe structuur moeilijker met elk bestandje dat je erbij maakt)

**Comment by DMooij** [comment]
Is het zo beter? We hadden wel mapjes data en resultaten gemaakt maar daar stond nog niks in dus die zijn niet op de git gekomen

**Comment by Tamrell** [comment]
dat is inderdaad een grote stap in de goede richting ;) ik zie jullie donderdag!
