### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by slanghout** [slanghout/Heuristieken#3]
Hallo,

Wij proberen een grid te maken wat bijhoudt wat er allemaal in de grid word gezet

Dit is de code  voor een 10x10 grid. We proberen dan op een vakje allemaal Y'tjes te zetten. Alleen pakt hij dan alleen de lengte en zet hij over de hele hoogte Y'tjes in plaats van dat hij alleen op een bepaalde hoogte dit doet. Weet jij waar dit mis gaat? 

class grid(object):
	def __init__(self, width, height):
		self.width = width
		self.height = height

	def hoimakegrid(self):
		grid = []
		row = []
		for x in range(self.width):
			row.append('0')
		for y in range(self.height):
			grid.append(row)
		# for i in range(len(grid)):
		# 	print(grid[i])
		return grid

	
	def hoioverlaping(self, cordinatelist, housecords):
		for i in range(housecords[0], (housecords[2])):
			for j in range(housecords[3], (housecords[1])):
				print(cordinatelist[i][j], j, i)
				if cordinatelist[i][j] == "0":
					cordinatelist[i][j] = "y"
				else:
					print("vol{}{}".format(j, i))
		return True

grids = grid(40, 40).hoimakegrid()

cord = [5, 20, 15, 10]

grid(40, 40).hoioverlaping(grids, cord)

print(grids)

**Comment by WouterVrielink** [comment]
Dat klopt! Denk terug aan C -> een list is eigenlijk een pointer. Dat betekent dat je iedere keer dezelfde list-verwijzing (row) aan het appenden bent aan de grid. Dus een verandering in één van de rows is een verandering in de originele array. Zie ook: https://stackoverflow.com/questions/2739552/2d-list-has-weird-behavor-when-trying-to-modify-a-single-value.
